name: Deploy website to Ali

on:
  push:
    branches: [master]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: yarn

      - name: Build source
        run: yarn build

      - name: Deploy to Ali
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SSH_TOKEN }}
          ARGS: '-avz --delete'
          SOURCE: './dist'
          REMOTE_HOST: ${{ secrets.ALI_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/opt/kanno-blog'

      - name: Reload pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALI_HOST }}
          username: 'root'
          key: ${{ secrets.ALIYUN_SSH_TOKEN }}
          script: |
            cd /opt/kanno-blog
            pm2 reload pm2.config.json
